version: 2

models:
  - name: test_hex
    tests:
      - assert_equal:
          actual: actual
          expected: expected

  - name: test_binary_literal
    tests:
      - assert_equal:
          actual: actual
          expected: expected

