
name: 'ethereum'
version: '1.0.0'
config-version: 2
profile: 'dbt_ethereum'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target" 
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ethereum:
    nft:
      +schema: nft
      +materialized: view

vars:
  ethereum:
    wyvern_atomic_match: "opensea.wyvernexchangev1_call_atomicmatch_"
