config-version: 2

name: "datawaves"
version: "1.0.0"
profile: "datawaves"

models:
  +file_format: delta

  datawaves:
    nft:
      +schema: nft

    labels:
      +schema: labels
      +materialized: ephemeral

    index:
      +schema: index
      +materialized: ephemeral
    
    cryptopunks:
      +schema: cryptopunks
      +materialized: view

    opensea:
      +schema: opensea
      +materialized: view
    
    ens:
      +schema: ens
      +materialized: view
seeds:
  datawaves:
    nft:
      +schema: nft
