
config-version: 2

name: 'ethereum'
version: '1.0.0'
profile: 'dbt_ethereum'

models:
  ethereum:
    nft:
      +materialized: view

    enrich:
      +materialized: view

vars:
  ethereum:
    wyvern_atomic_match: "opensea.wyvernexchangev1_call_atomicmatch_"
    erc20_tokens: "ethereum.tokens"