config-version: 2

name: "datawaves"
version: "1.0.0"
profile: "datawaves"

models:
  +file_format: delta

  datawaves:
    nft:
      +schema: nft
      +tags:
        - chain_ethereum
        - level_modeling
        - proj_nft

    labels:
      +schema: labels
      +tags:
        - chain_ethereum
        - level_modeling
        - proj_labels

    index:
      +schema: index
      +tags:
        - chain_ethereum
        - level_modeling
        - proj_index

seeds:
  datawaves:
    nft:
      +schema: nft

vars:
  start_ts: "1970-01-01"
  end_ts: "9999-01-01"
