config-version: 2

name: "datawaves"
version: "1.0.0"
profile: "datawaves"

models:
  +file_format: delta

  datawaves:
    erc20:
      +schema: erc20
      +tags: ['decoding']

    erc721:
      +schema: erc721
      +tags: ['decoding']

    erc1155:
      +schema: erc1155
      +tags: ['decoding']

    nft:
      +schema: nft
      +tags: ['abstraction']

    labels:
      +schema: labels
      +materialized: ephemeral
      +tags: ['abstraction']

    index:
      +schema: index
      +materialized: ephemeral
      +tags: ['abstraction']

    cryptopunks:
      +schema: cryptopunks
      +materialized: view
      +tags: ['decoding', 'abstraction']

    opensea:
      +schema: opensea
      +materialized: view
      +tags: ['decoding', 'abstraction']

    ens:
      +schema: ens
      +materialized: view
      +tags: ['decoding', 'abstraction']

    transfers:
      +schema: transfers
      +materialized: view
      +tags: ['abstraction']

seeds:
  datawaves:
    nft:
      +schema: nft
