config-version: 2

name: "datawaves"
version: "1.0.0"
profile: "datawaves"

models:
  +file_format: delta

  datawaves:
    erc20:
      +schema: erc20
      +tags: ['sector']

    erc721:
      +schema: erc721
      +tags: ['sector']

    erc1155:
      +schema: erc1155
      +tags: ['sector']

    nft:
      +schema: nft
      +tags: ['sector']

    transfers:
      +schema: transfers
      +materialized: view
      +tags: ['sector']

    cryptopunks:
      +schema: cryptopunks
      +materialized: view
      +tags: ['project']

    opensea:
      +schema: opensea
      +materialized: view
      +tags: ['project']

    ens:
      +schema: ens
      +materialized: view
      +tags: ['project']


seeds:
  datawaves:
    nft:
      +schema: nft
