config-version: 2

name: "datawaves"
version: "1.0.0"
profile: "datawaves"

models:
  +file_format: delta

  datawaves:
    nft:
      +schema: nft

    labels:
      +schema: labels

    index:
      +schema: index

seeds:
  datawaves:
    nft:
      +schema: nft
