
config-version: 2

name: 'ethereum'
version: '1.0.0'
profile: 'dbt_ethereum'

models:
  ethereum:
    nft:
      +schema: nft
      +materialized: view

    staging:
      +materialized: view

seeds:
  
  ethereum:
    nft:
      +schema: nft

vars:
  ethereum:    
    # ethereum-etl
    tokens: "ethereum.tokens"
    contracts: "ethereum.contracts"
    token_transfers: "ethereum.token_transfers"
    transactions: "ethereum.transactions"
  prices_usd: "prices.usd"
  start_ts: "1970-01-01"
  end_ts: "9999-01-01"