config-version: 2

name: "datawaves"
version: "1.0.0"
profile: "datawaves"

models:
  +file_format: delta

  datawaves:
    nft:
      +schema: nft

    labels:
      +schema: labels

    index:
      +schema: index


seeds:
  datawaves:
    nft:
      +schema: nft

vars:
  start_ts: "1970-01-01"
  end_ts: "9999-01-01"
  using_labels: false
  using_nft_mints: true
  using_nft_trades: true
