config-version: 2

name: "datawaves"
version: "1.0.0"
profile: "datawaves"

models:
  +file_format: delta

  datawaves:
    erc20:
      +schema: erc20

    erc721:
      +schema: erc721

    erc1155:
      +schema: erc1155

    nft:
      +schema: nft

    labels:
      +schema: labels
      +materialized: ephemeral

    index:
      +schema: index
      +materialized: ephemeral
    
    cryptopunks:
      +schema: cryptopunks
      +materialized: view

    opensea:
      +schema: opensea
      +materialized: view
    
    ens:
      +schema: ens
      +materialized: view

    transfers:
      +schema: transfers
      +materialized: view
seeds:
  datawaves:
    nft:
      +schema: nft
