
config-version: 2

name: 'ethereum'
version: '1.0.0'
profile: 'dbt_ethereum'

models:
  ethereum:
    nft:
      +schema: nft
      +materialized: view

    erc20:
      +schema: erc20
      +materialized: view

    erc721:
      +schema: erc721
      +materialized: view

    staging:
      +materialized: ephemeral

vars:
  ethereum:
    wyvern_atomic_match: "opensea.wyvernexchangev1_call_atomicmatch_"
    # ethereum-etl
    tokens: "ethereum.tokens"
    contracts: "ethereum.contracts"
    token_transfers: "ethereum.token_transfers"
