version: 2

models:
  - name: opensea_trader
    config:
      materialized: ephemeral
  - name: legendary_nft_trader
    config:
      materialized: ephemeral 
  - name: epic_nft_trader
    config:
      materialized: ephemeral 
  - name: rare_nft_trader
    config:
      materialized: ephemeral 
  - name: uncommon_nft_trader
    config:
      materialized: ephemeral 
  - name: diversified_nft_holder
    config:
      materialized: ephemeral 
  - name: blue_chip_nft_holder
    config:
      materialized: ephemeral 
