version: 2

models:
  - name: erc721_tokens
    columns:
      - name: contract_address
        description: The address of the ERC721 token.
      - name: symbol
        description: The symbol of the ERC721 token.
      - name: name
        description: The name of the ERC721 token.
      - name: decimals
        description: The number of decimals the token uses. 
      - name: total_supply
        description: The total token supply.

  - name: erc721_token_transfers
    columns:
      - name: token_address
        description: The address of the ERC721 token.
      - name: from_address
        description: Address of the sender.
      - name: to_address
        description: Address of the receiver.
      - name: token_id
        description: Id of the token transferred.
      - name: transaction_hash
        description: Transaction hash.
      - name: log_index
        description: Log index in the transaction receipt.
      - name: block_timestamp
        description: Timestamp of the block where this transfer was in.
      - name: block_number
        description: Block number where this transfer was in.
      - name: block_hash
        description: Hash of the block where this transfer was in.